name = "blocks"
version = "0.1.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
weft = { path = "../../../weft" }
weft_lustre = { path = "../../../weft_lustre" }
weft_lustre_ui = { path = "../../" }
